# Generated by Django 5.2.6 on 2025-09-12 17:22

import apps.defects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Если заполнено, объект считается удалённым', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(help_text='Название категории дефектов', max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Подробное описание категории', verbose_name='Описание категории')),
                ('color', models.CharField(default='#007bff', help_text='Цвет для отображения в интерфейсе (hex)', max_length=7, verbose_name='Цвет категории')),
                ('icon', models.CharField(blank=True, help_text='Название иконки для отображения', max_length=50, verbose_name='Иконка категории')),
                ('is_active', models.BooleanField(default=True, help_text='Доступна ли категория для использования', verbose_name='Активная')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок отображения в списках', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория дефекта',
                'verbose_name_plural': 'Категории дефектов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Если заполнено, объект считается удалённым', null=True, verbose_name='Дата удаления')),
                ('title', models.CharField(help_text='Краткое описание дефекта', max_length=200, verbose_name='Заголовок дефекта')),
                ('description', models.TextField(help_text='Подробное описание дефекта', verbose_name='Описание дефекта')),
                ('defect_number', models.CharField(blank=True, help_text='Автоматически генерируемый номер дефекта', max_length=50, unique=True, verbose_name='Номер дефекта')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', help_text='Приоритет устранения дефекта', max_length=20, verbose_name='Приоритет')),
                ('location', models.TextField(help_text='Детальное описание местоположения дефекта', verbose_name='Местоположение')),
                ('floor', models.CharField(blank=True, help_text='Этаж, на котором находится дефект', max_length=20, verbose_name='Этаж')),
                ('room', models.CharField(blank=True, help_text='Помещение, в котором находится дефект', max_length=100, verbose_name='Помещение')),
                ('coordinates_x', models.DecimalField(blank=True, decimal_places=2, help_text='X координата на плане (в пикселях или метрах)', max_digits=10, null=True, verbose_name='Координата X')),
                ('coordinates_y', models.DecimalField(blank=True, decimal_places=2, help_text='Y координата на плане (в пикселях или метрах)', max_digits=10, null=True, verbose_name='Координата Y')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], default='new', help_text='Текущий статус дефекта', max_length=20, verbose_name='Статус дефекта')),
                ('due_date', models.DateField(blank=True, help_text='Плановая дата устранения дефекта', null=True, verbose_name='Срок устранения')),
                ('assigned_at', models.DateTimeField(blank=True, help_text='Дата назначения исполнителя', null=True, verbose_name='Дата назначения')),
                ('started_at', models.DateTimeField(blank=True, help_text='Дата начала работ по устранению', null=True, verbose_name='Дата начала работ')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Дата завершения работ по устранению', null=True, verbose_name='Дата завершения')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Дата закрытия дефекта после проверки', null=True, verbose_name='Дата закрытия')),
                ('severity', models.CharField(choices=[('cosmetic', 'Косметический'), ('minor', 'Незначительный'), ('major', 'Значительный'), ('critical', 'Критический'), ('blocking', 'Блокирующий')], default='minor', help_text='Серьёзность дефекта', max_length=20, verbose_name='Серьёзность')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Ориентировочная стоимость устранения в рублях', max_digits=12, null=True, verbose_name='Ориентировочная стоимость устранения')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Фактическая стоимость устранения в рублях', max_digits=12, null=True, verbose_name='Фактическая стоимость устранения')),
                ('resolution_description', models.TextField(blank=True, help_text='Описание способа устранения дефекта', verbose_name='Описание решения')),
                ('prevention_measures', models.TextField(blank=True, help_text='Меры для предотвращения подобных дефектов в будущем', verbose_name='Меры предотвращения')),
                ('external_id', models.CharField(blank=True, help_text='ID дефекта во внешней системе', max_length=100, verbose_name='Внешний ID')),
                ('assignee', models.ForeignKey(blank=True, help_text='Пользователь, ответственный за устранение дефекта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('author', models.ForeignKey(help_text='Пользователь, создавший дефект', on_delete=django.db.models.deletion.PROTECT, related_name='authored_defects', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('project', models.ForeignKey(help_text='Проект, к которому относится дефект', on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='projects.project', verbose_name='Проект')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Пользователь, проверяющий устранение дефекта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_defects', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
                ('stage', models.ForeignKey(blank=True, help_text='Этап проекта, на котором выявлен дефект', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='projects.projectstage', verbose_name='Этап проекта')),
                ('category', models.ForeignKey(help_text='Категория дефекта', on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='defects.defectcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Дефект',
                'verbose_name_plural': 'Дефекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Если заполнено, объект считается удалённым', null=True, verbose_name='Дата удаления')),
                ('content', models.TextField(help_text='Текст комментария', verbose_name='Содержание комментария')),
                ('comment_type', models.CharField(choices=[('comment', 'Комментарий'), ('status_change', 'Изменение статуса'), ('assignment', 'Назначение'), ('resolution', 'Решение'), ('rejection', 'Отклонение')], default='comment', help_text='Тип комментария', max_length=20, verbose_name='Тип комментария')),
                ('is_internal', models.BooleanField(default=False, help_text='Виден только участникам проекта', verbose_name='Внутренний комментарий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defects.defect', verbose_name='Дефект')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='defects.defectcomment', verbose_name='Ответ на комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий к дефекту',
                'verbose_name_plural': 'Комментарии к дефектам',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Если заполнено, объект считается удалённым', null=True, verbose_name='Дата удаления')),
                ('file', models.FileField(help_text='Загруженный файл', upload_to=apps.defects.models.defect_image_path, verbose_name='Файл')),
                ('filename', models.CharField(help_text='Оригинальное имя файла', max_length=255, verbose_name='Имя файла')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('document', 'Документ'), ('video', 'Видео'), ('audio', 'Аудио'), ('other', 'Другое')], help_text='Тип загруженного файла', max_length=20, verbose_name='Тип файла')),
                ('file_size', models.PositiveIntegerField(help_text='Размер файла в байтах', verbose_name='Размер файла')),
                ('mime_type', models.CharField(blank=True, help_text='MIME тип файла', max_length=100, verbose_name='MIME тип')),
                ('description', models.TextField(blank=True, help_text='Описание содержимого файла', verbose_name='Описание файла')),
                ('is_main', models.BooleanField(default=False, help_text='Является ли файл основным изображением дефекта', verbose_name='Основное изображение')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='defects.defect', verbose_name='Дефект')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загружен пользователем')),
            ],
            options={
                'verbose_name': 'Файл дефекта',
                'verbose_name_plural': 'Файлы дефектов',
                'ordering': ['-is_main', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Тип выполненного действия', max_length=50, verbose_name='Действие')),
                ('field_name', models.CharField(blank=True, help_text='Название изменённого поля', max_length=50, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, help_text='Значение до изменения', verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, help_text='Значение после изменения', verbose_name='Новое значение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='defects.defect', verbose_name='Дефект')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История изменений дефекта',
                'verbose_name_plural': 'История изменений дефектов',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['project', 'status'], name='defects_def_project_f276a3_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['assignee', 'status'], name='defects_def_assigne_5e8895_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['author'], name='defects_def_author__c32c75_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['category'], name='defects_def_categor_94bd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['priority', 'status'], name='defects_def_priorit_484958_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['due_date'], name='defects_def_due_dat_23a8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['defect_number'], name='defects_def_defect__1d1d3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='defect',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost__gte', 0)), name='positive_estimated_cost'),
        ),
        migrations.AddConstraint(
            model_name='defect',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cost__gte', 0)), name='positive_actual_cost'),
        ),
        migrations.AddIndex(
            model_name='defectcomment',
            index=models.Index(fields=['defect', 'created_at'], name='defects_def_defect__905e85_idx'),
        ),
        migrations.AddIndex(
            model_name='defectcomment',
            index=models.Index(fields=['author'], name='defects_def_author__a5c21e_idx'),
        ),
        migrations.AddIndex(
            model_name='defecthistory',
            index=models.Index(fields=['defect', 'timestamp'], name='defects_def_defect__82b177_idx'),
        ),
        migrations.AddIndex(
            model_name='defecthistory',
            index=models.Index(fields=['user'], name='defects_def_user_id_cefc38_idx'),
        ),
    ]
