# Generated by Django 5.2.6 on 2025-09-12 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Если заполнено, объект считается удалённым', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(help_text='Уникальное название проекта', max_length=200, unique=True, verbose_name='Название проекта')),
                ('slug', models.SlugField(blank=True, help_text='Автоматически генерируется из названия', max_length=200, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(help_text='Подробное описание проекта', verbose_name='Описание проекта')),
                ('address', models.TextField(help_text='Полный адрес строительного объекта', verbose_name='Адрес объекта')),
                ('coordinates_lat', models.DecimalField(blank=True, decimal_places=8, help_text='Координаты объекта (широта)', max_digits=10, null=True, verbose_name='Широта')),
                ('coordinates_lng', models.DecimalField(blank=True, decimal_places=8, help_text='Координаты объекта (долгота)', max_digits=11, null=True, verbose_name='Долгота')),
                ('customer', models.CharField(help_text='Название организации-заказчика', max_length=300, verbose_name='Заказчик')),
                ('customer_contact', models.CharField(blank=True, help_text='ФИО контактного лица', max_length=200, verbose_name='Контактное лицо заказчика')),
                ('customer_phone', models.CharField(blank=True, help_text='Контактный телефон', max_length=20, verbose_name='Телефон заказчика')),
                ('customer_email', models.EmailField(blank=True, help_text='Контактный email', max_length=254, verbose_name='Email заказчика')),
                ('contract_number', models.CharField(blank=True, help_text='Номер договора с заказчиком', max_length=100, verbose_name='Номер договора')),
                ('contract_date', models.DateField(blank=True, help_text='Дата заключения договора', null=True, verbose_name='Дата договора')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Общая сумма договора в рублях', max_digits=15, null=True, verbose_name='Сумма договора')),
                ('start_date', models.DateField(help_text='Плановая дата начала проекта', verbose_name='Дата начала')),
                ('end_date', models.DateField(help_text='Плановая дата завершения проекта', verbose_name='Дата завершения')),
                ('actual_start_date', models.DateField(blank=True, help_text='Фактическая дата начала работ', null=True, verbose_name='Фактическая дата начала')),
                ('actual_end_date', models.DateField(blank=True, help_text='Фактическая дата завершения работ', null=True, verbose_name='Фактическая дата завершения')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('in_progress', 'В работе'), ('on_hold', 'Приостановлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='planning', help_text='Текущий статус проекта', max_length=20, verbose_name='Статус проекта')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', help_text='Приоритет проекта', max_length=20, verbose_name='Приоритет')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, help_text='Общая площадь строительства', max_digits=10, null=True, verbose_name='Общая площадь (м²)')),
                ('building_type', models.CharField(blank=True, choices=[('residential', 'Жилое'), ('commercial', 'Коммерческое'), ('industrial', 'Промышленное'), ('infrastructure', 'Инфраструктура'), ('other', 'Другое')], help_text='Тип строительного объекта', max_length=100, verbose_name='Тип здания')),
                ('floors_count', models.PositiveSmallIntegerField(blank=True, help_text='Количество этажей в здании', null=True, verbose_name='Количество этажей')),
                ('notify_on_defect_creation', models.BooleanField(default=True, help_text='Отправлять уведомления при создании дефектов', verbose_name='Уведомлять о новых дефектах')),
                ('notify_on_status_change', models.BooleanField(default=True, help_text='Отправлять уведомления при изменении статусов дефектов', verbose_name='Уведомлять об изменении статусов')),
                ('manager', models.ForeignKey(help_text='Ответственный менеджер проекта', on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Менеджер'), ('engineer', 'Инженер'), ('observer', 'Наблюдатель'), ('coordinator', 'Координатор')], default='engineer', help_text='Роль пользователя в проекте', max_length=20, verbose_name='Роль в проекте')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Дата присоединения к проекту', verbose_name='Дата присоединения')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли участник в проекте', verbose_name='Активный участник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='projects.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проектов',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(help_text='Пользователи, участвующие в проекте', related_name='projects', through='projects.ProjectMember', to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта'),
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Если заполнено, объект считается удалённым', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(help_text='Название этапа работ', max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, help_text='Подробное описание этапа', verbose_name='Описание этапа')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок выполнения этапа', verbose_name='Порядок')),
                ('start_date', models.DateField(help_text='Плановая дата начала этапа', verbose_name='Дата начала')),
                ('end_date', models.DateField(help_text='Плановая дата завершения этапа', verbose_name='Дата завершения')),
                ('actual_start_date', models.DateField(blank=True, help_text='Фактическая дата начала этапа', null=True, verbose_name='Фактическая дата начала')),
                ('actual_end_date', models.DateField(blank=True, help_text='Фактическая дата завершения этапа', null=True, verbose_name='Фактическая дата завершения')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В работе'), ('completed', 'Завершён'), ('on_hold', 'Приостановлен'), ('cancelled', 'Отменён')], default='not_started', help_text='Текущий статус этапа', max_length=20, verbose_name='Статус этапа')),
                ('estimated_hours', models.PositiveIntegerField(blank=True, help_text='Планируемое количество часов на этап', null=True, verbose_name='Плановые часы')),
                ('actual_hours', models.PositiveIntegerField(blank=True, help_text='Фактически затраченные часы', null=True, verbose_name='Фактические часы')),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0, help_text='Процент выполнения этапа (0-100)', verbose_name='Процент выполнения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='Проект')),
                ('responsible', models.ForeignKey(blank=True, help_text='Ответственный за этап', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_stages', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Этап проекта',
                'verbose_name_plural': 'Этапы проектов',
                'ordering': ['project', 'order', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Если заполнено, объект считается удалённым', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(help_text='Название шаблона проекта', max_length=200, unique=True, verbose_name='Название шаблона')),
                ('description', models.TextField(help_text='Описание назначения шаблона', verbose_name='Описание шаблона')),
                ('building_type', models.CharField(choices=[('residential', 'Жилое'), ('commercial', 'Коммерческое'), ('industrial', 'Промышленное'), ('infrastructure', 'Инфраструктура'), ('other', 'Другое')], help_text='Тип строительного объекта', max_length=100, verbose_name='Тип здания')),
                ('is_active', models.BooleanField(default=True, help_text='Доступен ли шаблон для использования', verbose_name='Активный')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон проекта',
                'verbose_name_plural': 'Шаблоны проектов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название этапа работ', max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, help_text='Описание этапа', verbose_name='Описание этапа')),
                ('order', models.PositiveSmallIntegerField(help_text='Порядок выполнения этапа', verbose_name='Порядок')),
                ('estimated_days', models.PositiveIntegerField(help_text='Планируемая продолжительность этапа в днях', verbose_name='Планируемая длительность (дни)')),
                ('estimated_hours', models.PositiveIntegerField(blank=True, help_text='Планируемое количество часов на этап', null=True, verbose_name='Плановые часы')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='projects.projecttemplate', verbose_name='Шаблон проекта')),
            ],
            options={
                'verbose_name': 'Шаблон этапа',
                'verbose_name_plural': 'Шаблоны этапов',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'is_active'], name='projects_pr_project_e48af9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'is_active'], name='projects_pr_user_id_5f83f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager'], name='projects_pr_manager_6dc9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date', 'end_date'], name='projects_pr_start_d_dfae95_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority'], name='projects_pr_priorit_a3d3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_ae7d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['responsible'], name='projects_pr_respons_59b59a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['start_date', 'end_date'], name='projects_pr_start_d_d2e5bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectstage',
            unique_together={('project', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='projectstagetemplate',
            unique_together={('template', 'order')},
        ),
    ]
