# Generated by Django 5.2.6 on 2025-09-12 17:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Уникальный email адрес пользователя', max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер проекта'), ('engineer', 'Инженер'), ('observer', 'Наблюдатель')], default='engineer', help_text='Роль пользователя в системе', max_length=20, verbose_name='Роль')),
                ('first_name', models.CharField(help_text='Имя пользователя', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия пользователя', max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, help_text='Отчество пользователя (опционально)', max_length=150, verbose_name='Отчество')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер телефона пользователя', max_length=128, region=None, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, help_text='Должность на предприятии', max_length=200, verbose_name='Должность')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Подтверждён ли email адрес', verbose_name='Email подтверждён')),
                ('must_change_password', models.BooleanField(default=True, help_text='Требуется ли смена пароля при следующем входе', verbose_name='Необходимо сменить пароль')),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='Дата последней смены пароля', null=True, verbose_name='Дата смены пароля')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP адрес последнего входа в систему', null=True, verbose_name='IP последнего входа')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Количество неудачных попыток входа подряд', verbose_name='Неудачные попытки входа')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Время до которого аккаунт заблокирован', null=True, verbose_name='Заблокирован до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Если заполнено, объект считается удалённым', null=True, verbose_name='Дата удаления')),
                ('avatar', models.ImageField(blank=True, help_text='Фотография пользователя', upload_to='avatars/%Y/%m/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, help_text='Краткая информация о пользователе', max_length=500, verbose_name='О себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('department', models.CharField(blank=True, help_text='Отдел/подразделение', max_length=200, verbose_name='Отдел')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма на работу')),
                ('email_notifications', models.BooleanField(default=True, help_text='Получать уведомления по email', verbose_name='Email уведомления')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Получать уведомления по SMS', verbose_name='SMS уведомления')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('auto', 'Автоматическая')], default='light', max_length=20, verbose_name='Тема интерфейса')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=10, verbose_name='Язык интерфейса')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сессии')),
                ('ip_address', models.GenericIPAddressField(help_text='IP адрес пользователя', verbose_name='IP адрес')),
                ('user_agent', models.TextField(help_text='Информация о браузере', verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало сессии')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='users_users_user_id_3887fe_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='users_users_session_70af4d_idx'),
        ),
    ]
